# Form implementation generated from reading ui file 'Admin-HCMS.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 598)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(245, 250, 254);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(31, 149, 239);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    height:30px;\n"
"    border:none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:#F5FAFE;\n"
"    color:#1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Img/anvata.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnThongTinKhachHang_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.btnThongTinKhachHang_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Img/ThongTinKhachHang.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnThongTinKhachHang_1.setIcon(icon)
        self.btnThongTinKhachHang_1.setCheckable(True)
        self.btnThongTinKhachHang_1.setAutoExclusive(True)
        self.btnThongTinKhachHang_1.setObjectName("btnThongTinKhachHang_1")
        self.verticalLayout.addWidget(self.btnThongTinKhachHang_1)
        self.btnDanhSachLichHen_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.btnDanhSachLichHen_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Img/DanhSachDichVu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDanhSachLichHen_1.setIcon(icon1)
        self.btnDanhSachLichHen_1.setCheckable(True)
        self.btnDanhSachLichHen_1.setAutoExclusive(True)
        self.btnDanhSachLichHen_1.setObjectName("btnDanhSachLichHen_1")
        self.verticalLayout.addWidget(self.btnDanhSachLichHen_1)
        self.btnDanhSachHoaDon_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.btnDanhSachHoaDon_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Img/trend-analysis-svgrepo-com.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDanhSachHoaDon_1.setIcon(icon2)
        self.btnDanhSachHoaDon_1.setCheckable(True)
        self.btnDanhSachHoaDon_1.setAutoExclusive(True)
        self.btnDanhSachHoaDon_1.setObjectName("btnDanhSachHoaDon_1")
        self.verticalLayout.addWidget(self.btnDanhSachHoaDon_1)
        self.btnDanhSachDichVu_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.btnDanhSachDichVu_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Img/DanhSachLichHen.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDanhSachDichVu_1.setIcon(icon3)
        self.btnDanhSachDichVu_1.setCheckable(True)
        self.btnDanhSachDichVu_1.setAutoExclusive(True)
        self.btnDanhSachDichVu_1.setObjectName("btnDanhSachDichVu_1")
        self.verticalLayout.addWidget(self.btnDanhSachDichVu_1)
        self.btnBaoCaoThongKe_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.btnBaoCaoThongKe_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/Img/BaoCaoThongKe.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnBaoCaoThongKe_1.setIcon(icon4)
        self.btnBaoCaoThongKe_1.setCheckable(True)
        self.btnBaoCaoThongKe_1.setAutoExclusive(True)
        self.btnBaoCaoThongKe_1.setObjectName("btnBaoCaoThongKe_1")
        self.verticalLayout.addWidget(self.btnBaoCaoThongKe_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 261, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.btnDangXuat_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.btnDangXuat_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/Img/CaiDat.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDangXuat_1.setIcon(icon5)
        self.btnDangXuat_1.setCheckable(True)
        self.btnDangXuat_1.setAutoExclusive(True)
        self.btnDangXuat_1.setObjectName("btnDangXuat_1")
        self.verticalLayout_3.addWidget(self.btnDangXuat_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_name_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_name_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(31, 149, 239);\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    text-align:left;\n"
"    height:30px;\n"
"    border:none;\n"
"    padding-left:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color:#F5FAFE;\n"
"    color:#1F95EF;\n"
"    font-weight:bold;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.icon_name_widget)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_name_widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/Img/anvata.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnThongTinKhachHang_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.btnThongTinKhachHang_2.setIcon(icon)
        self.btnThongTinKhachHang_2.setCheckable(True)
        self.btnThongTinKhachHang_2.setAutoExclusive(True)
        self.btnThongTinKhachHang_2.setObjectName("btnThongTinKhachHang_2")
        self.verticalLayout_2.addWidget(self.btnThongTinKhachHang_2)
        self.btnDanhSachLichHen_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.btnDanhSachLichHen_2.setIcon(icon1)
        self.btnDanhSachLichHen_2.setCheckable(True)
        self.btnDanhSachLichHen_2.setAutoExclusive(True)
        self.btnDanhSachLichHen_2.setObjectName("btnDanhSachLichHen_2")
        self.verticalLayout_2.addWidget(self.btnDanhSachLichHen_2)
        self.btnDanhSachHoaDon_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.btnDanhSachHoaDon_2.setIcon(icon2)
        self.btnDanhSachHoaDon_2.setCheckable(True)
        self.btnDanhSachHoaDon_2.setAutoExclusive(True)
        self.btnDanhSachHoaDon_2.setObjectName("btnDanhSachHoaDon_2")
        self.verticalLayout_2.addWidget(self.btnDanhSachHoaDon_2)
        self.btnDanhSachDichVu_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.btnDanhSachDichVu_2.setIcon(icon3)
        self.btnDanhSachDichVu_2.setCheckable(True)
        self.btnDanhSachDichVu_2.setAutoExclusive(True)
        self.btnDanhSachDichVu_2.setObjectName("btnDanhSachDichVu_2")
        self.verticalLayout_2.addWidget(self.btnDanhSachDichVu_2)
        self.btnBaoCaoThongKe_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.btnBaoCaoThongKe_2.setIcon(icon4)
        self.btnBaoCaoThongKe_2.setCheckable(True)
        self.btnBaoCaoThongKe_2.setAutoExclusive(True)
        self.btnBaoCaoThongKe_2.setObjectName("btnBaoCaoThongKe_2")
        self.verticalLayout_2.addWidget(self.btnBaoCaoThongKe_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 270, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.btnDangXuat_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.btnDangXuat_2.setCheckable(True)
        self.btnDangXuat_2.setAutoExclusive(True)
        self.btnDangXuat_2.setObjectName("btnDangXuat_2")
        self.gridLayout_2.addWidget(self.btnDangXuat_2, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_hcms = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_hcms.setObjectName("main_hcms")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_hcms)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(parent=self.main_hcms)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnTabBar = QtWidgets.QPushButton(parent=self.widget)
        self.btnTabBar.setStyleSheet("border:none;\n"
"")
        self.btnTabBar.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/Img/siderbar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTabBar.setIcon(icon6)
        self.btnTabBar.setIconSize(QtCore.QSize(20, 20))
        self.btnTabBar.setCheckable(True)
        self.btnTabBar.setObjectName("btnTabBar")
        self.horizontalLayout_4.addWidget(self.btnTabBar)
        spacerItem2 = QtWidgets.QSpacerItem(154, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtTimKiem = QtWidgets.QLineEdit(parent=self.widget)
        self.txtTimKiem.setObjectName("txtTimKiem")
        self.horizontalLayout.addWidget(self.txtTimKiem)
        self.btnTimKiem = QtWidgets.QPushButton(parent=self.widget)
        self.btnTimKiem.setStyleSheet("border-radius:10px;")
        self.btnTimKiem.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/Img/search-folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTimKiem.setIcon(icon7)
        self.btnTimKiem.setObjectName("btnTimKiem")
        self.horizontalLayout.addWidget(self.btnTimKiem)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(153, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_15.setStyleSheet("border:none;")
        self.pushButton_15.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/Img/anvata.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_15.setIcon(icon8)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_4.addWidget(self.pushButton_15)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_hcms)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_ThongTinKhachHang = QtWidgets.QWidget()
        self.page_ThongTinKhachHang.setObjectName("page_ThongTinKhachHang")
        self.tblThongTinKhachHang = QtWidgets.QTableWidget(parent=self.page_ThongTinKhachHang)
        self.tblThongTinKhachHang.setGeometry(QtCore.QRect(10, 10, 531, 421))
        self.tblThongTinKhachHang.setObjectName("tblThongTinKhachHang")
        self.tblThongTinKhachHang.setColumnCount(0)
        self.tblThongTinKhachHang.setRowCount(0)
        self.btnThemTTkhachHang = QtWidgets.QPushButton(parent=self.page_ThongTinKhachHang)
        self.btnThemTTkhachHang.setGeometry(QtCore.QRect(30, 470, 75, 23))
        self.btnThemTTkhachHang.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnThemTTkhachHang.setObjectName("btnThemTTkhachHang")
        self.btnSuaTTkhachHang = QtWidgets.QPushButton(parent=self.page_ThongTinKhachHang)
        self.btnSuaTTkhachHang.setGeometry(QtCore.QRect(230, 470, 75, 23))
        self.btnSuaTTkhachHang.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnSuaTTkhachHang.setObjectName("btnSuaTTkhachHang")
        self.btnXoaTTKhacHang = QtWidgets.QPushButton(parent=self.page_ThongTinKhachHang)
        self.btnXoaTTKhacHang.setGeometry(QtCore.QRect(430, 470, 75, 23))
        self.btnXoaTTKhacHang.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnXoaTTKhacHang.setObjectName("btnXoaTTKhacHang")
        self.stackedWidget.addWidget(self.page_ThongTinKhachHang)
        self.page_DanhSachLichHen = QtWidgets.QWidget()
        self.page_DanhSachLichHen.setObjectName("page_DanhSachLichHen")
        self.tblDachSachLichHen = QtWidgets.QTableWidget(parent=self.page_DanhSachLichHen)
        self.tblDachSachLichHen.setGeometry(QtCore.QRect(20, 20, 531, 421))
        self.tblDachSachLichHen.setObjectName("tblDachSachLichHen")
        self.tblDachSachLichHen.setColumnCount(0)
        self.tblDachSachLichHen.setRowCount(0)
        self.btnXoaLichHen = QtWidgets.QPushButton(parent=self.page_DanhSachLichHen)
        self.btnXoaLichHen.setGeometry(QtCore.QRect(440, 480, 75, 23))
        self.btnXoaLichHen.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnXoaLichHen.setObjectName("btnXoaLichHen")
        self.btnThemLichHen = QtWidgets.QPushButton(parent=self.page_DanhSachLichHen)
        self.btnThemLichHen.setGeometry(QtCore.QRect(40, 480, 75, 23))
        self.btnThemLichHen.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnThemLichHen.setObjectName("btnThemLichHen")
        self.btnSuaLichHen = QtWidgets.QPushButton(parent=self.page_DanhSachLichHen)
        self.btnSuaLichHen.setGeometry(QtCore.QRect(240, 480, 75, 23))
        self.btnSuaLichHen.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnSuaLichHen.setObjectName("btnSuaLichHen")
        self.stackedWidget.addWidget(self.page_DanhSachLichHen)
        self.page_DanhSachHoaDon = QtWidgets.QWidget()
        self.page_DanhSachHoaDon.setObjectName("page_DanhSachHoaDon")
        self.tblDanhSachHoaDon = QtWidgets.QTableWidget(parent=self.page_DanhSachHoaDon)
        self.tblDanhSachHoaDon.setGeometry(QtCore.QRect(20, 20, 531, 421))
        self.tblDanhSachHoaDon.setObjectName("tblDanhSachHoaDon")
        self.tblDanhSachHoaDon.setColumnCount(0)
        self.tblDanhSachHoaDon.setRowCount(0)
        self.btnXoaHoaDon = QtWidgets.QPushButton(parent=self.page_DanhSachHoaDon)
        self.btnXoaHoaDon.setGeometry(QtCore.QRect(440, 480, 75, 23))
        self.btnXoaHoaDon.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnXoaHoaDon.setObjectName("btnXoaHoaDon")
        self.btnThemHoaDon = QtWidgets.QPushButton(parent=self.page_DanhSachHoaDon)
        self.btnThemHoaDon.setGeometry(QtCore.QRect(40, 480, 75, 23))
        self.btnThemHoaDon.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnThemHoaDon.setObjectName("btnThemHoaDon")
        self.btnSuaHoaDon = QtWidgets.QPushButton(parent=self.page_DanhSachHoaDon)
        self.btnSuaHoaDon.setGeometry(QtCore.QRect(240, 480, 75, 23))
        self.btnSuaHoaDon.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnSuaHoaDon.setObjectName("btnSuaHoaDon")
        self.stackedWidget.addWidget(self.page_DanhSachHoaDon)
        self.page_DanHSachDichVu = QtWidgets.QWidget()
        self.page_DanHSachDichVu.setObjectName("page_DanHSachDichVu")
        self.tblDanhSachDichVu = QtWidgets.QTableWidget(parent=self.page_DanHSachDichVu)
        self.tblDanhSachDichVu.setGeometry(QtCore.QRect(20, 30, 531, 421))
        self.tblDanhSachDichVu.setObjectName("tblDanhSachDichVu")
        self.tblDanhSachDichVu.setColumnCount(0)
        self.tblDanhSachDichVu.setRowCount(0)
        self.btnXoaDichVu = QtWidgets.QPushButton(parent=self.page_DanHSachDichVu)
        self.btnXoaDichVu.setGeometry(QtCore.QRect(440, 490, 75, 23))
        self.btnXoaDichVu.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnXoaDichVu.setObjectName("btnXoaDichVu")
        self.btnThemDichVu = QtWidgets.QPushButton(parent=self.page_DanHSachDichVu)
        self.btnThemDichVu.setGeometry(QtCore.QRect(40, 490, 75, 23))
        self.btnThemDichVu.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnThemDichVu.setObjectName("btnThemDichVu")
        self.btnSuaDichVu = QtWidgets.QPushButton(parent=self.page_DanHSachDichVu)
        self.btnSuaDichVu.setGeometry(QtCore.QRect(240, 490, 75, 23))
        self.btnSuaDichVu.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"")
        self.btnSuaDichVu.setObjectName("btnSuaDichVu")
        self.stackedWidget.addWidget(self.page_DanHSachDichVu)
        self.page_BaoCaoThongKe = QtWidgets.QWidget()
        self.page_BaoCaoThongKe.setObjectName("page_BaoCaoThongKe")
        self.ThongKe = QtWidgets.QTabWidget(parent=self.page_BaoCaoThongKe)
        self.ThongKe.setGeometry(QtCore.QRect(10, 20, 541, 491))
        self.ThongKe.setObjectName("ThongKe")
        self.ThongKeTheQuy = QtWidgets.QWidget()
        self.ThongKeTheQuy.setObjectName("ThongKeTheQuy")
        self.ThongKe.addTab(self.ThongKeTheQuy, "")
        self.ThongKeTheoDoanhThu = QtWidgets.QWidget()
        self.ThongKeTheoDoanhThu.setObjectName("ThongKeTheoDoanhThu")
        self.ThongKe.addTab(self.ThongKeTheoDoanhThu, "")
        self.stackedWidget.addWidget(self.page_BaoCaoThongKe)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.main_hcms, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.ThongKe.setCurrentIndex(0)
        self.btnTabBar.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.btnTabBar.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.btnDanhSachDichVu_1.toggled['bool'].connect(self.btnDanhSachDichVu_2.setChecked) # type: ignore
        self.btnDanhSachHoaDon_1.toggled['bool'].connect(self.btnDanhSachHoaDon_2.setChecked) # type: ignore
        self.btnDanhSachLichHen_1.toggled['bool'].connect(self.btnDanhSachLichHen_2.setChecked) # type: ignore
        self.btnThongTinKhachHang_1.toggled['bool'].connect(self.btnThongTinKhachHang_2.setChecked) # type: ignore
        self.btnThongTinKhachHang_2.toggled['bool'].connect(self.btnThongTinKhachHang_1.setChecked) # type: ignore
        self.btnDanhSachLichHen_2.toggled['bool'].connect(self.btnDanhSachLichHen_1.setChecked) # type: ignore
        self.btnDanhSachHoaDon_2.toggled['bool'].connect(self.btnDanhSachHoaDon_1.setChecked) # type: ignore
        self.btnDanhSachDichVu_2.toggled['bool'].connect(self.btnDanhSachDichVu_1.setChecked) # type: ignore
        self.btnDangXuat_1.toggled['bool'].connect(self.btnDangXuat_1.close) # type: ignore
        self.btnDangXuat_2.toggled['bool'].connect(self.btnDangXuat_2.close) # type: ignore
        self.btnDangXuat_1.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.btnDangXuat_2.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.btnBaoCaoThongKe_2.toggled['bool'].connect(self.btnBaoCaoThongKe_1.setChecked) # type: ignore
        self.btnBaoCaoThongKe_1.toggled['bool'].connect(self.btnBaoCaoThongKe_2.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Nhóm 3"))
        self.btnThongTinKhachHang_2.setText(_translate("MainWindow", "Thông tin khách hàng"))
        self.btnDanhSachLichHen_2.setText(_translate("MainWindow", "Danh sách lịch hẹn"))
        self.btnDanhSachHoaDon_2.setText(_translate("MainWindow", "Danh sách hoá đơn"))
        self.btnDanhSachDichVu_2.setText(_translate("MainWindow", "Danh sách dịch vụ"))
        self.btnBaoCaoThongKe_2.setText(_translate("MainWindow", "Báo cáo thông kê"))
        self.btnDangXuat_2.setText(_translate("MainWindow", "Đăng Xuất"))
        self.btnThemTTkhachHang.setText(_translate("MainWindow", "Thêm"))
        self.btnSuaTTkhachHang.setText(_translate("MainWindow", "Sửa"))
        self.btnXoaTTKhacHang.setText(_translate("MainWindow", "Xoá"))
        self.btnXoaLichHen.setText(_translate("MainWindow", "Xoá"))
        self.btnThemLichHen.setText(_translate("MainWindow", "Thêm"))
        self.btnSuaLichHen.setText(_translate("MainWindow", "Sửa"))
        self.btnXoaHoaDon.setText(_translate("MainWindow", "Xoá"))
        self.btnThemHoaDon.setText(_translate("MainWindow", "Thêm"))
        self.btnSuaHoaDon.setText(_translate("MainWindow", "Sửa"))
        self.btnXoaDichVu.setText(_translate("MainWindow", "Xoá"))
        self.btnThemDichVu.setText(_translate("MainWindow", "Thêm"))
        self.btnSuaDichVu.setText(_translate("MainWindow", "Sửa"))
        self.ThongKe.setTabText(self.ThongKe.indexOf(self.ThongKeTheQuy), _translate("MainWindow", "Thống Kê Theo Quý"))
        self.ThongKe.setTabText(self.ThongKe.indexOf(self.ThongKeTheoDoanhThu), _translate("MainWindow", "Thống kê Theo DoanhThu"))
